// Code generated by goctl. DO NOT EDIT.
package types

type ArticleDetailRequest struct {
	ArticleId int64 `json:"article_id"`
}

type ArticleDetailResponse struct {
	Article ArticleItem `json:"article_item"`
}

type ArticleItem struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Description  string `json:"description"`
	Cover        string `json:"cover"`
	CommentCount int64  `json:"comment_count"`
	LikeCount    int64  `json:"like_count"`
	PublishTime  int64  `json:"publish_time"`
	AuthorId     int64  `json:"author_id"`
}

type ArticlesRequest struct {
	Cursor    int64 `json:"cursor"`
	PageSize  int64 `json:"page_size"`
	SortType  int32 `json:"sort_type"`
	ArticleId int64 `json:"article_id"`
}

type ArticlesResponse struct {
	Articles  []ArticleItem `json:"articles"`
	IsEnd     bool          `json:"is_end"`
	Cursor    int64         `json:"cursor"`
	ArticleId int64         `json:"article_id"`
}

type DeleteArticleRequest struct {
	ArticleId int64 `json:"article_id"`
}

type DeleteArticleResponse struct {
	DeleteMessage string `json:"delete_message"`
}

type PublishRequest struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	Description string `json:"description"`
	Cover       string `json:"cover"`
}

type PublishResponse struct {
	ArticleId int64 `json:"article_id"`
}

type UploadCoverResponse struct {
	CoverUrl string `json:"cover_url"`
}
