// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"myzhihu/apps/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/articleDetail",
				Handler: ArticleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/articles",
				Handler: ArticlesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deleteArticle",
				Handler: DeleteArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: PublishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload/cover",
				Handler: UploadCoverHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/article"),
	)
}
